### ISSUE TITLE
Support for different Sizes

### ISSUE THREAD

**Issue by zubairshokh** [kemonomachi/experhash#4] opened 2018-03-29 12:46 UTC
Email Convo about the issue

For DD-Hash.

```c++
for(int i = 0; i < SIZE; ++i) {
for(int j = 0; j < SIZE; ++j) {
row_hash[i] |= (pixels[i*SIZE + j] < pixels[i*SIZE + j+1]) << (7-j);
        col_hash[i] |= (pixels[i + j*SIZE] < pixels[(i + (j+1)*SIZE)%PIXEL_COUNT + j/8]) << (7-j);
      }
    }
```
here you are shifting by `(7-j)`

If we change the size from `8 to 32 or 64`, how will that effect on the algorithm. 

Hi Zubair,

I'm using vectors of 8-bit integers to assemble the hash, which means
that the shifting distance (7-j) should be independent of the size.
Currently it is not, and it is not possible to change the size because
of that. This needs fixing.

I'll need to look it over before I can give you a definite answer. It's
been a while since I wrote this. If possible, could you open an issue
about this on Github? [1] Feel free to include this mail.

I'm going out of town for the Easter holiday soon, so I won't have time
until next week. I'll get back to you next weekend. If you have any
additional questions, please feel free to ask.

- Ookami

**- Need to work on that**

**Comment by kemonomachi** [comment] 2018-04-08 19:29
Right. `SIZE` currently can't be changed due to how I implemented the bit twiddling.

I'm gonna play around a bit with `std::bitset` and `boost::dynamic_bitset`, to see if I can find a more convenient way to represent the hash data. Keeping `vector<uint8_t>` could also work, but it requires an additional arithmetic step and is already kind of messy.

I also need to relax the spec on the Elixir side, since it specifies a 128-bit hash.

Out of curiosity, why do you want the added granularity increasing `SIZE` would give you? Bumping dd_hash to 64x64 will increase the hash size to 8192 bits, which seems a little excessive.

**Comment by zubairshokh** [comment] 2018-04-09 04:07
@kemonomachi using 8x8, image losses the details.[minute details], increasing size can retain certain amount of details to identify the image as next to unique.

**Comment by Faolain** [comment] 2018-05-01 03:52
Wish I knew enough to be able to help out here but if it means anything I also agree some increased granularity would help in reducing collisions. Something like 16x16 would increase specificity while keeping the hash size to a somewhat reasonable level.

**Comment by kemonomachi** [comment] 2018-05-02 20:07
@zubairshokh I apologize for the delay. I'll try to fix this during the upcoming weekend.

@Faolain Good to know that others want this increased granularity as well.

**Comment by kemonomachi** [comment] 2018-05-06 14:32
I want to fix the tests first (#3), so this will take a while longer.

**Comment by kemonomachi** [comment] 2018-05-11 20:10
I have finally found some time to think about this, and to read up on perceptual hash algorithms again, and I've decided not to implement this. dHash focuses on speed over accuracy, and increasing the hash size would run counter to that philosophy (not that this implementation is particularly optimized, mind you).

If you need higher precision, you're better off with a different algorithm, like [pHash](http://phash.org/), instead. ImageMagick has it as an option for its `compare` command, if you want to try it out.

Closing this issue.

**Comment by Faolain** [comment] 2018-05-11 21:02
@kemonomachi in the blog you linked there is the following excerpt:

"I have tried a few variations of the dHash algorithm. For example, David's initial proposal used an 8x8 image and wrapped the last comparison (computing the pixel difference between P[0] and P[7] for the 8th comparison). This actually performs a little worse than my 9x8 variation (more false-positives), but only by a little."

which seems to point out that the 9x8 variation is superior to a 8x8 with wrapping which I believe is the current implementation as per the Experhash README. It seems like either an option to add the extra granularity or switching to 9x8 would perform slightly better without much of a speed impact.

**Comment by kemonomachi** [comment] 2018-05-12 17:34
@Faolain Yeah, I can't remember why I choose the wrapping version to be honest. I think I'll change it to 9x8 instead (9x9 for ddHash). I'll create a separate issue for that.

I'll actually open this one again, since I've figured out a way to implement this using templates which will keep the same level of efficiency (I think) without any (manual) code duplication. First attempt looks good anyway.

The problem is how to represent the hashes in C++. Ideally I'd want an arbitrarily long sequence of bits that can be easily turned into a sequence of bytes (for sending it back to Elixir). `std::bitset` fits the first requirement, but not the second.  `boost::dynamic_bitset` might work, but it feels like overkill to pull in all of boost just for this.

Vectors are not quite ideal either since the bits are "packed" in groups of 8, 16, 32 etc. depending on the type of the elements. With `uint8_t` and an 8x8 image, one element corresponds to the bits from one row of the shrunken image. This keeps things manageable. When upping the size of the hash, I want to also scale up the size of the elements, to keep this correspondence. Using templates I can pretty much keep the current code and have the compiler generate specialized versions for 8x8, 16x16, 32x32, and 64x64 pixels, using the appropriate types.

**Comment by kemonomachi** [comment] 2018-06-22 10:21
I've finally added this functionality (01c2dfc6fc26a35342b2cf305ed6193ce4506b66), sorry for taking so long!

@zubairshokh, @Faolain: If you are still interested in this, could you try it out and see if it matches your expectations? The functions now have the bit-size at the end, so you could use for instance `d_hash_256` or `dd_hash_8192` (see the README for all sizes).

The current implementation will give different results depending on the endian-ness of the underlying system, so don't try to compare hashes computed on different architectures!

**Closed** 2019-04-25 17:04 UTC
Labels: enhancement

**Comment by Faolain** [comment] 2019-04-27 05:18
thanks so much @kemonomachi !
